spring:
  application:
    name: delivery
  profiles:
    active: local

server:
  port: 8090

redis:
  key-format:
    delivery-status:
      key: "delivery:%d:status"
      ttl: 30m
    delivery-store:
      key: "delivery:store:%d:active-deliveries"
      ttl: 1h

  channel-format:
    delivery-update: "delivery:update:%d"
